/*******************************************************************************
** CalcGUI.java                                                               **
** -------------------------------------------------------------------------- **
** Graphical user interface. Based on code generated by NetBeans IDE.         **
** -------------------------------------------------------------------------- **
** Developed by Leon Byford <ldjb20@bath.ac.uk>                               **
** Last modified: 1 January 2013                                              **
*******************************************************************************/

// import swing package
import javax.swing.*;
public class CalcGUI extends JFrame {

	// declare interface components
	private JButton Button;
	private JTextField TextField;
	
	// GUI constructor
	public CalcGUI() {
		initComponents();
	}

	// initialise components
	private void initComponents() {

		TextField = new JTextField();
		Button = new JButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("Java Calculator");
		setResizable(false);

		TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		TextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FormSubmitted();
			}
		});

		Button.setText("Calculate");
		Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		Button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FormSubmitted();
			}
		});

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(
						  GroupLayout.Alignment.CENTER)
					.addComponent(Button)
					.addComponent(TextField, GroupLayout.DEFAULT_SIZE,
								  388, Short.MAX_VALUE))
				.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(TextField, GroupLayout.PREFERRED_SIZE,
							  GroupLayout.DEFAULT_SIZE,
							  GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(Button)
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		pack();
	}

	// when form is submitted
	private void FormSubmitted() {
		// determine result of calculation
		String result = CalcIO.process(TextField.getText());
		// if the result is valid
		if (result != null) {
			// display result in text field
			TextField.setText(result);
		}
		// if the result is invalid
		else {
			// display error message in text field
			TextField.setText("Error. Please try again.");
		}
		// set focus on text field
		TextField.requestFocus();
		// select all text in text field
		TextField.selectAll();
	}

	// GUI initialisation
	public static void initAll() {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CalcGUI().setVisible(true);
			}
		});
	}

}